### ISSUE TITLE
AssertionError:

### ISSUE THREAD

**Issue by molyswu** [nelson-liu/paraphrase-id-tensorflow#63]
Hi,
python scripts/run_model/run_siamese.py train --share_encoder_weights --model_name=baseline_siamese --run_id=0
Traceback (most recent call last):
  File "scripts/run_model/run_siamese.py", line 14, in <module>
    from duplicate_questions.data.instances.sts_instance import STSInstance
  File "scripts/run_model/../../duplicate_questions/data/instances/sts_instance.py", line 122, in <module>
    class IndexedSTSInstance(IndexedInstance):
  File "scripts/run_model/../../duplicate_questions/data/instances/sts_instance.py", line 366, in IndexedSTSInstance
    @overrides
  File "/usr/lib/python2.7/site-packages/overrides/overrides.py", line 70, in overrides
    method.__name__)
AssertionError: No super class method found for "__eq__"

Thank you!
molyswu

**Comment by nelson-liu** [comment]
Can you verify that you are using python 3.5? This look like a incompatible python version error.

**Comment by molyswu** [comment]
python3.5 :
 python3.5 scripts/run_model/run_siamese.py train --share_encoder_weights --model_name=baseline_siamese --run_id=0
Traceback (most recent call last):
  File "scripts/run_model/run_siamese.py", line 7, in <module>
    import pandas as pd
ImportError: No module named 'pandas'
[root@localhost paraphrase-id-tensorflow-master]# 
molyswu

**Comment by nelson-liu** [comment]
Did you install all of the requirements?

**Comment by molyswu** [comment]
[root@localhost paraphrase-id-tensorflow-master]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>>

**Comment by nelson-liu** [comment]
Not sure what your last comment means -- did you run pip install -r requirements.txt ?

**Comment by molyswu** [comment]
Hi,
# python3 scripts/run_model/run_siamese.py train --share_encoder_weights --model_name=baseline_siamese --run_id=0
2017-05-25 09:28:15,390 - INFO - duplicate_questions.data.data_manager - Getting training data from ['scripts/run_model/../../data/processed/quora/train_cleaned_train_split.csv']
2017-05-25 09:28:15,390 - INFO - duplicate_questions.data.dataset - Reading files ['scripts/run_model/../../data/processed/quora/train_cleaned_train_split.csv'] to a list of lines.
Traceback (most recent call last):
  File "scripts/run_model/run_siamese.py", line 254, in <module>
    main()
  File "scripts/run_model/run_siamese.py", line 142, in main
    max_lengths={"num_sentence_words": num_sentence_words})
  File "scripts/run_model/../../duplicate_questions/data/data_manager.py", line 140, in get_train_data_from_file
    self.instance_type)
  File "scripts/run_model/../../duplicate_questions/data/dataset.py", line 142, in read_from_file
    lines = [x.strip() for filename in filenames
  File "scripts/run_model/../../duplicate_questions/data/dataset.py", line 144, in <listcomp>
    "r", "utf-8").readlines())]
  File "/usr/local/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'scripts/run_model/../../data/processed/quora/train_cleaned_train_split.csv'

**Comment by nelson-liu** [comment]
you need to get and clean the data before running the model. see https://github.com/nelson-liu/paraphrase-id-tensorflow#getting--processing-the-data

**Comment by molyswu** [comment]
Hi,
make quora_data
./scripts/data/quora/clean_and_split_quora_dataset.sh
Making quora folder in data/interim/ if it does not exist
Cleaning the raw train and test CSVs
2017-05-25 09:42:16,530 - INFO - __main__ - Reading csv at ../../../data/raw/train.csv
2017-05-25 09:42:16,530 - INFO - __main__ - Cleaning csv
Traceback (most recent call last):
  File "clean_quora_dataset.py", line 60, in <module>
    main()
  File "clean_quora_dataset.py", line 32, in main
    with open(config.dataset_input_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../../data/raw/train.csv'
2017-05-25 09:42:16,562 - INFO - __main__ - Reading csv at ../../../data/raw/test.csv
2017-05-25 09:42:16,562 - INFO - __main__ - Cleaning csv
Traceback (most recent call last):
  File "clean_quora_dataset.py", line 60, in <module>
    main()
  File "clean_quora_dataset.py", line 32, in main
    with open(config.dataset_input_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../../data/raw/test.csv'
Making quora folder in data/processed/ if it does not exist
Splitting the train CSV into train and val and moving it to data/processed/quora
2017-05-25 09:42:16,595 - INFO - __main__ - Reading csv at ../../../data/interim/quora/train_cleaned.csv
Traceback (most recent call last):
  File "split_quora_file.py", line 66, in <module>
    main()
  File "split_quora_file.py", line 32, in main
    with open(config.dataset_input_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../../data/interim/quora/train_cleaned.csv'
Copying the cleaned test CSV into data/processed/quora
cp: didn 't get "../../../data/interim/quora/test_cleaned.csv" 的文件状态(stat): 没有那个文件或目录
make: *** [quora_data] 错误 1

**Comment by nelson-liu** [comment]
did you run `make aux_dirs`? Can you pull from master? there was a bug recently that was fixed with the script.

**Comment by molyswu** [comment]
make aux_dirs
./scripts/data/make_auxiliary_dirs.sh
Creating auxiliary directories
Done creating auxiliary directories

**Comment by nelson-liu** [comment]
did you get the kaggle data and unzip it in the proper place?

**Comment by molyswu** [comment]
Hi
I can not download the network, you can send a Kaggle  data to my email sasunwu@126.com.

Thank you very much!

**Comment by nelson-liu** [comment]
the data is too large to be sent by email, so you're going to have to find another way :/ sorry. can you not access kaggle?

**Comment by nelson-liu** [comment]
closing as nonresponse
