### ISSUE TITLE
remove the overrides , otherwise it reports error

### ISSUE THREAD

**Issue by loveJasmine** [nelson-liu/paraphrase-id-tensorflow#66]
Traceback (most recent call last):
  File "scripts/run_model/run_siamese_matching_bilstm.py", line 16, in <module>
    from duplicate_questions.data.instances.sts_instance import STSInstance
  File "scripts/run_model/../../duplicate_questions/data/instances/sts_instance.py", line 13, in <module>
    class STSInstance(TextInstance):
  File "scripts/run_model/../../duplicate_questions/data/instances/sts_instance.py", line 69, in STSInstance
    @overrides
  File "/home//f.local/lib/python3.6/site-packages/overrides/overrides.py", line 70, in overrides
    method.__name__)
AssertionError: No super class method found for "words"

**Comment by nelson-liu** [comment]
Sorry, are you still getting this error / need help? It's not clear to me why you closed this...

**Comment by loveJasmine** [comment]
1.9

**Comment by nelson-liu** [comment]
I see, must be python 3.6 specific since CI (on Python 3.5) passes. But you're right --- removing all the @overrides should fix it.
